model:
  name: DecoderModel1
  notes: >
    This is Decoder Model 1 configuration file.
    Design Guidelines:
    - The layers should alternate between conv_layer and conv_transpose_layer.
    - in_channels of conv_transpose_layer should be multiple of out_channels of previous conv_layer (e.g., 4*4=16).
    - Before Final Conv Layer the layers should alternate between conv_layer and conv_transpose_layer.
  blocks:
    - id: ConvBlock_1
      type: conv_layer
      params:
        in_channels: 1
        out_channels: 4
        kernel_size: 3
        stride: 1
        padding: 1
        activation: ReLU
        batch_norm: True
    - id: ConvTBlock_1
      type: conv_transpose_layer
      params:
        in_channels: 16 # In channels should be multiple of out_channels of previous conv_layer (4*4=16)
        out_channels: 4 
        kernel_size: 7
        stride: 5
        padding: 1
        activation: LeakyReLU
        batch_norm: True
    - id: ConvBlock_2
      type: conv_layer
      params:
        in_channels: 4
        out_channels: 8
        kernel_size: 3
        stride: 1
        padding: 1
        activation: ReLU
        batch_norm: True
    - id: ConvTBlock_2
      type: conv_transpose_layer
      params:
        in_channels: 32
        out_channels: 8
        kernel_size: 6
        stride: 2
        padding: 1
        activation: LeakyReLU
        batch_norm: True
# Before Final Conv Layer the layers should alternate between conv_layer and conv_transpose_layer
    - id: FinalConvLayer
      type: final_conv_layer
      params:
        in_channels: 8
        out_channels: 2
        kernel_size: 4
        stride: 1
        padding: 1
        