model:
  name: EncoderModel1
  blocks:
    - id: ConvLayer
      type: layer1
      params:
        in_channels: 3
        out_channels: 4
        kernel_size: 3
        stride: 1
        padding: 1
        activation: ReLU
        batch_norm: True
    - id: ConvLayer2
      type: layer1
      params:
        in_channels: 4
        out_channels: 8
        kernel_size: 5
        stride: 1
        padding: 2
        activation: LeakyReLU
        batch_norm: True
    - id: ConvLayerFreq
      type: squish_freq
      params:
        in_channels: 8
        out_channels: 4
        kernel_size: (5, 3)
        stride: (4, 1)
        padding: (2, 1)
        activation: ReLU
        batch_norm: True
    - id: ConvLayerTime
      type: squish_time
      params:
        in_channels: 8
        out_channels: 4
        kernel_size: (3, 5)
        stride: (1, 4)
        padding: (1, 2)
        activation: LeakyReLU
        batch_norm: True
    - id: MergedNodeConv
      type: merge_node
      params:
        in_channels: 64
        out_channels: 32
        kernel_size: 4
        stride: 1
        padding: 1
        batch_norm: True
        activation: LeakyReLU
    - id: SecondaryConv1
      type: secondarylayer
      params:
        in_channels: 8
        out_channels: 4
        kernel_size: 6
        stride: 2
        padding: 2
        batch_norm: True
        activation: LeakyReLU
    - id: SecondaryConv2
      type: secondarylayer
      params:
        in_channels: 4
        out_channels: 2
        kernel_size: 7
        stride: 5
        padding: 1
        batch_norm: False
        activation: None
    
    